-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (User Settings)
create table public.profiles (
  id uuid references auth.users not null primary key,
  organization_name text,
  lead_time_days int default 2,
  safety_stock_loads int default 6,
  dashboard_layout jsonb,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- 2. PRODUCTS (SKUs)
create table public.products (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  bottles_per_case int not null default 12,
  bottles_per_truck int not null default 0,
  cases_per_pallet int not null default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table public.products enable row level security;
create policy "Users can view own products" on public.products for select using (auth.uid() = user_id);
create policy "Users can insert own products" on public.products for insert with check (auth.uid() = user_id);
create policy "Users can update own products" on public.products for update using (auth.uid() = user_id);
create policy "Users can delete own products" on public.products for delete using (auth.uid() = user_id);

-- 3. PLANNING ENTRIES (Sparse Data: Demand, Actuals, Inbound)
create table public.planning_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  product_id uuid references public.products(id) on delete cascade not null,
  date date not null,
  entry_type text not null check (entry_type in ('demand_plan', 'production_actual', 'inbound_trucks')),
  value numeric not null,
  updated_at timestamptz default now()
);

alter table public.planning_entries enable row level security;
create policy "Users can view own entries" on public.planning_entries for select using (auth.uid() = user_id);
create policy "Users can all own entries" on public.planning_entries for all using (auth.uid() = user_id);

-- Unique index to prevent duplicates (Upsert support)
create unique index idx_planning_entries_unique on public.planning_entries (user_id, product_id, date, entry_type);

-- 4. INVENTORY SNAPSHOTS (Anchors)
create table public.inventory_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  product_id uuid references public.products(id) on delete cascade not null,
  date date not null,
  location text not null check (location in ('floor', 'yard')),
  quantity_pallets numeric default 0, -- For Floor
  quantity_loads numeric default 0,   -- For Yard
  meta jsonb,
  created_at timestamptz default now()
);

alter table public.inventory_snapshots enable row level security;
create policy "Users can view own snapshots" on public.inventory_snapshots for select using (auth.uid() = user_id);
create policy "Users can all own snapshots" on public.inventory_snapshots for all using (auth.uid() = user_id);

-- 5. PRODUCTION SETTINGS (Per Product)
create table public.production_settings (
  product_id uuid references public.products(id) on delete cascade primary key,
  user_id uuid references auth.users not null default auth.uid(),
  production_rate int default 0,
  downtime_hours numeric default 0,
  is_auto_replenish boolean default true,
  updated_at timestamptz default now()
);

alter table public.production_settings enable row level security;
create policy "Users can view own settings" on public.production_settings for select using (auth.uid() = user_id);
create policy "Users can all own settings" on public.production_settings for all using (auth.uid() = user_id);

-- Trigger to handle updated_at
create or replace function handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_planning_entries_update
  before update on public.planning_entries
  for each row execute procedure handle_updated_at();

create trigger on_production_settings_update
  before update on public.production_settings
  for each row execute procedure handle_updated_at();

-- Trigger to create profile after signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
